apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt

resources:
  - "namespace.yaml"
  - "pvc.yaml"
  - "deployment.yaml"
  - "secret.yaml"

components:
  - ../../components/external-secrets-transformer

images:
  - name: koenkk/zigbee2mqtt
    newTag: 1.39.0
