apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.6.0
  - linstor-cluster.yaml
  - linstor-satellite-configuration.yaml
